# Generated by Django 3.2 on 2021-05-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0005_alter_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Data aula')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='persons.student')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='persons.teacher')),
            ],
        ),
    ]
