# Generated by Django 3.2 on 2021-05-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_alter_class_teacher'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Data aula')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='persons.class')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='persons.teacher')),
            ],
        ),
    ]
