# Generated by Django 3.2 on 2021-05-18 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_alter_class_teacher'),
        ('schedule', '0002_groupclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclass',
            name='students_presente',
            field=models.ManyToManyField(related_name='_schedule_groupclass_students_presente_+', to='schedule.GroupClass', verbose_name='Alunos presentes'),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='theme',
            field=models.CharField(default='Aula de música', max_length=100, verbose_name='Tema da aula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualclass',
            name='theme',
            field=models.CharField(default='Aula de musica', max_length=100, verbose_name='Tema da aula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='persons.class', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='persons.teacher', verbose_name='Professor(a)'),
        ),
        migrations.AlterField(
            model_name='individualclass',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='persons.student', verbose_name='Aluno(a)'),
        ),
        migrations.AlterField(
            model_name='individualclass',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='persons.teacher', verbose_name='Professor'),
        ),
    ]
