# Generated by Django 3.2.3 on 2021-05-21 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_auto_20210520_1839'),
        ('schedule', '0006_auto_20210521_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclass',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.group', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.teacher', verbose_name='Professor(a)'),
        ),
    ]
