# Generated by Django 3.2 on 2021-05-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='specialty',
            field=models.ManyToManyField(to='courses.Course', verbose_name='Especialidade'),
        ),
    ]
