# Generated by Django 3.2 on 2021-05-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='id',
            new_name='id_p',
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='persons.teacher', verbose_name='Professor(a)'),
            preserve_default=False,
        ),
    ]
