# Generated by Django 3.2 on 2021-05-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20210518_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persons.teacher', verbose_name='Professor(a) da turma'),
        ),
    ]
