# Generated by Django 3.2 on 2021-05-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('persons', '0005_alter_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='especification',
            field=models.CharField(default=3, max_length=30, verbose_name='Descrição da Turma'),
            preserve_default=False,
        ),
    ]
