# Generated by Django 3.2.3 on 2021-05-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('schedule', '0005_rename_students_presente_groupclass_students_presents'),
        ('persons', '0006_auto_20210518_2018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Group',
        ),
    ]
