# Generated by Django 3.2.3 on 2021-05-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_rename_class_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='id_s',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='id_p',
            new_name='id_t',
        ),
    ]
